# Generated by Django 6.0.5 on 2026-05-11 22:14

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('single', 'Single'), ('contract', 'Contract')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_amount_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='CoworkingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, to='Coworkhub.location')),
            ],
            options={
                'db_table': 'coworkingcenter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.PROTECT, to='Coworkhub.member')),
            ],
            options={
                'db_table': 'contract',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'membershipplan',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='membershipplan_discount_range')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.member')),
                ('plan', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='Coworkhub.membershipplan')),
            ],
            options={
                'db_table': 'membership',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('coworking_center', models.ForeignKey(db_column='coworking_center_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.coworkingcenter')),
            ],
            options={
                'db_table': 'workspace',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valid_from', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('price_per_slot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.workspace')),
            ],
            options={
                'db_table': 'workspacesetup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SetupEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.PROTECT, to='Coworkhub.equipment')),
                ('setup', models.ForeignKey(db_column='setup_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.workspacesetup')),
            ],
            options={
                'db_table': 'setupequipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contract', models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coworkhub.contract')),
                ('invoice', models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coworkhub.invoice')),
                ('responsible_member', models.ForeignKey(db_column='responsible_member_id', on_delete=django.db.models.deletion.PROTECT, to='Coworkhub.member')),
                ('setup', models.ForeignKey(db_column='setup_id', on_delete=django.db.models.deletion.PROTECT, to='Coworkhub.workspacesetup')),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipmentComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('child_equipment', models.ForeignKey(db_column='child_equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='Coworkhub.equipment')),
                ('parent_equipment', models.ForeignKey(db_column='parent_equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Coworkhub.equipment')),
            ],
            options={
                'db_table': 'equipmentcomposition',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('parent_equipment', 'child_equipment'), name='uniq_equip_comp')],
            },
        ),
        migrations.CreateModel(
            name='MemberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.member')),
            ],
            options={
                'db_table': 'memberemail',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('member', 'email'), name='uniq_member_email')],
            },
        ),
        migrations.CreateModel(
            name='ReservationParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.member')),
                ('reservation', models.ForeignKey(db_column='reservation_id', on_delete=django.db.models.deletion.CASCADE, to='Coworkhub.reservation')),
            ],
            options={
                'db_table': 'reservationparticipants',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('reservation', 'member'), name='uniq_res_participant')],
            },
        ),
        migrations.AddConstraint(
            model_name='workspacesetup',
            constraint=models.UniqueConstraint(fields=('workspace', 'version_number'), name='uniq_workspace_version'),
        ),
        migrations.AddConstraint(
            model_name='setupequipment',
            constraint=models.UniqueConstraint(fields=('setup', 'equipment'), name='uniq_setup_equipment'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('setup', 'date', 'slot'), name='uniq_res_setup_date_slot'),
        ),
    ]
