# Generated by Django 6.0.5 on 2026-05-12 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coworkhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Coworkhub.member'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contract',
            field=models.ForeignKey(blank=True, db_column='contract_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='Coworkhub.contract'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='responsible_member',
            field=models.ForeignKey(db_column='responsible_member_id', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_reservations', to='Coworkhub.member'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='coworking_center',
            field=models.ForeignKey(db_column='coworking_center_id', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='Coworkhub.coworkingcenter'),
        ),
        migrations.AlterField(
            model_name='workspacesetup',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='Coworkhub.workspace'),
        ),
    ]
