apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: coworkhub
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: coworking_db
  DB_USER: postgres
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,coworkhub.local,slider-sleet-mango.ngrok-free.dev"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://coworkhub.local,http://127.0.0.1:59032,https://slider-sleet-mango.ngrok-free.dev"